Adapt build system to new layout.
Gbp-Dch: Ignore

diff --git a/debian/patches/01_build.sh.diff b/debian/patches/01_build.sh.diff
--- a/debian/patches/01_build.sh.diff
+++ b/debian/patches/01_build.sh.diff
@@ -1,104 +1,80 @@
-From: Michele Cane <michele.cane@gmail.com>
-Subject: adapt upstream build.sh to Debian
-Origin: vendor, Debian
-Last-Updated: 2012-01-25
-
---- a/build.sh
-+++ b/build.sh
-@@ -102,8 +102,8 @@ if [ ! -z "$SYMLINK_DIR" ]; then
- 	if [ $? != 0 ]; then
- 		exit
- 	fi
--	REV=`git log -n 1 --pretty='format:%h'`
--	VERSION="$DEFAULT_VERSION_PREFIX$REV"
-+###no-debian	REV=`git log -n 1 --pretty='format:%h'`
-+###no-debian	VERSION="$DEFAULT_VERSION_PREFIX$REV"
- 	find . -depth -type d -name .git -exec rm -rf {} \;
- 	
- 	# Windows can't actually symlink; copy instead, with a note
-@@ -138,7 +138,7 @@ else
- 	
- 	# Copy Zotero directory
- 	cd "$CALLDIR/modules/zotero"
--	REV=`git log -n 1 --pretty='format:%h'`
-+###no-debian	REV=`git log -n 1 --pretty='format:%h'`
- 	cp -RH "$CALLDIR/modules/zotero" "$BUILDDIR/zotero"
- 	cd "$BUILDDIR/zotero"
- 	
-@@ -435,21 +435,22 @@ fi
+Description: Adapt build.sh and build_xpi_4.0 to Debian needs.
+Author: Michele Cane <michele.cane@gmail.com>
+Author: Sébastien Villemot <sebastien@debian.org>
+Last-Updated: 2017-01-17
+Forwarded: not-needed
+---
+This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
+--- a/zotero-standalone-build/build.sh
++++ b/zotero-standalone-build/build.sh
+@@ -418,29 +418,12 @@ fi
  
  # Linux
  if [ $BUILD_LINUX == 1 ]; then
 -	for arch in "i686" "x86_64"; do
 -		RUNTIME_PATH=`eval echo '$LINUX_'$arch'_RUNTIME_PATH'`
-+###no-debian	for arch in "i686" "x86_64"; do
-+###no-debian		RUNTIME_PATH=`eval echo '$LINUX_'$arch'_RUNTIME_PATH'`
-+		arch=$DEB_BUILD_GNU_CPU
- 		
+-		
  		# Set up directory
- 		echo 'Building Zotero_linux-'$arch
--		APPDIR="$STAGEDIR/Zotero_linux-$arch"
-+		APPDIR="$STAGEDIR/zotero-standalone"
+-		echo 'Building Zotero_linux-'$arch
+-		APPDIR="$STAGE_DIR/Zotero_linux-$arch"
++		echo 'Building zotero-standalone'
++		APPDIR="$STAGE_DIR/zotero-standalone"
  		rm -rf "$APPDIR"
  		mkdir "$APPDIR"
  		
- 		# Merge xulrunner and relevant assets
- 		cp -R "$BUILDDIR/zotero/"* "$BUILDDIR/application.ini" "$APPDIR"
--		cp -r "$RUNTIME_PATH" "$APPDIR/xulrunner"
--		rm "$APPDIR/xulrunner/xulrunner-stub"
--		cp "$CALLDIR/linux/xulrunner-stub-$arch" "$APPDIR/zotero"
--		chmod 755 "$APPDIR/zotero"
-+###no-debian		cp -r "$RUNTIME_PATH" "$APPDIR/xulrunner"
-+###no-debian		rm "$APPDIR/xulrunner/xulrunner-stub"
-+###no-debian		cp "$CALLDIR/linux/xulrunner-stub-$arch" "$APPDIR/zotero"
-+###no-debian		chmod 755 "$APPDIR/zotero"
- 	
- 		# Add Unix-specific Standalone assets
+-		# Merge relevant assets from Firefox
+-		cp -r "$RUNTIME_PATH/"!(application.ini|browser|defaults|crashreporter|crashreporter.ini|firefox-bin|precomplete|removed-files|run-mozilla.sh|update-settings.ini|updater|updater.ini) "$APPDIR"
+-		
+-		# Use our own launcher that calls the original Firefox executable with -app
+-		mv "$APPDIR"/firefox "$APPDIR"/zotero-bin
+-		cp "$CALLDIR/linux/zotero" "$APPDIR"/zotero
+-		
+-		# Copy Ubuntu launcher files
+-		cp "$CALLDIR/linux/zotero.desktop" "$APPDIR"
+-		cp "$CALLDIR/linux/set_launcher_icon" "$APPDIR"
+-		
+-		# Use our own updater, because Mozilla's requires updates signed by Mozilla
+-		cp "$CALLDIR/linux/updater-$arch" "$APPDIR"/updater
+-		
+ 		cp -R "$BUILD_DIR/zotero/"* "$BUILD_DIR/application.ini" "$APPDIR"
+ 		
+ 		# Modify platform-specific prefs
+@@ -450,20 +433,9 @@ if [ $BUILD_LINUX == 1 ]; then
  		cd "$CALLDIR/assets/unix"
-@@ -457,20 +458,21 @@ if [ $BUILD_LINUX == 1 ]; then
+ 		zip -0 -r -q "$APPDIR/zotero.jar" *
  		
- 		# Add word processor plug-ins
- 		mkdir "$APPDIR/extensions"
+-		# Add word processor plug-ins
+-		mkdir "$APPDIR/extensions"
 -		cp -RH "$CALLDIR/modules/zotero-libreoffice-integration" "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org"
--		perl -pi -e 's/SOURCE<\/em:version>/SA.'"$VERSION"'<\/em:version>/' "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org/install.rdf"
-+		cp -RH "$CALLDIR/modules/zotero-libreoffice-integration" "$STAGEDIR"
-+		perl -pi -e 's/SOURCE<\/em:version>/SA.'"$VERSION"'<\/em:version>/' "$STAGEDIR/zotero-libreoffice-integration/install.rdf"
- 		rm -rf "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org/.git"
- 		
+-		perl -pi -e 's/\.SOURCE<\/em:version>/.SA.'"$VERSION"'<\/em:version>/' "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org/install.rdf"
+-		echo
+-		echo -n "$ext Version: "
+-		perl -ne 'print and last if s/.*<em:version>(.*)<\/em:version>.*/\1/;' "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org/install.rdf"
+-		echo
+-		rm -rf "$APPDIR/extensions/zoteroOpenOfficeIntegration@zotero.org/.git"
+-		
  		# Delete extraneous files
  		find "$APPDIR" -depth -type d -name .git -exec rm -rf {} \;
  		find "$APPDIR" \( -name .DS_Store -or -name update.rdf \) -exec rm -f {} \;
 -		find "$APPDIR/extensions" -depth -type d -name build -exec rm -rf {} \;
-+###no-debian		find "$STAGEDIR/zotero-libreoffice-integration" -depth -type d -name build -exec rm -rf {} \;
  		
  		# Add run-zotero.sh
- 		cp "$CALLDIR/linux/run-zotero.sh" "$APPDIR/run-zotero.sh"
- 		
- 		# Move icons, so that updater.png doesn't fail
--		mv "$APPDIR/xulrunner/icons" "$APPDIR/icons"
-+### updater.png in /usr/share/xulrunner-9.0/icons/updater.png
-+###no-debian 		mv "$APPDIR/xulrunner/icons" "$APPDIR/icons"
- 		
- 		if [ $PACKAGE == 1 ]; then
- 			# Create tar
-@@ -478,7 +480,7 @@ if [ $BUILD_LINUX == 1 ]; then
- 			cd "$STAGEDIR"
- 			tar -cjf "$DISTDIR/Zotero-${VERSION}_linux-$arch.tar.bz2" "Zotero_linux-$arch"
+ 		#cp "$CALLDIR/linux/run-zotero.sh" "$APPDIR/run-zotero.sh"
+@@ -474,7 +446,6 @@ if [ $BUILD_LINUX == 1 ]; then
+ 			cd "$STAGE_DIR"
+ 			tar -cjf "$DIST_DIR/Zotero-${VERSION}_linux-$arch.tar.bz2" "Zotero_linux-$arch"
  		fi
 -	done
-+###no-debian	done
  fi
  
- rm -rf $BUILDDIR
---- a/config.sh
-+++ b/config.sh
-@@ -36,7 +36,8 @@ DEFAULT_VERSION_PREFIX="4.0.999.SOURCE."
- VERSION_NUMERIC="4.0.999"
+ rm -rf $BUILD_DIR
+--- a/zotero-build/xpi/build_xpi_4.0
++++ b/zotero-build/xpi/build_xpi_4.0
+@@ -78,7 +78,6 @@ if [ -z "$VERSION" ]; then
+ 	echo "Version number not found in install.rdf"
+ 	exit 1
+ fi
+-HASH=`git -C "$REPO_DIR" rev-parse --short HEAD`
  
- # Directory for building
--BUILDDIR="/tmp/zotero-build-`uuidgen | head -c 8`"
-+###no-debian	BUILDDIR="/tmp/zotero-build-`uuidgen | head -c 8`"
-+BUILDDIR="$CALLDIR/build"
- # Directory for unpacked binaries
- STAGEDIR="$CALLDIR/staging"
- # Directory for packed binaries
+ # Export a clean copy of the tree
+ rsync -a --exclude=".git*" "$REPO_DIR/" "$TEMPDIR/zotero/"
